// packing-list.service.ts

import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class PackingListService {
  packingLists: { [activity: string]: string[] } = {
    standard: [
      'telefon',
      'ładowarka',
      'słuchawki',
      'laptop',
      'książka',
      'bielizna',
      'piżama',
      'ręcznik',
      'odzież',
      'kurtka przeciwdeszczowa',
      'czapka/kapelusz',
      'buty',
      'pieniądze',
      'dowód osobisty',
      'paszport',
      'prawo jazdy',
      'nerka',
      'szczoteczka i pasta do zębów',
      'dezodorant',
      'szampon',
      'żel pod prysznic',
      'chusteczki higieniczne',
      'mokre chusteczki',
      'apteczka',
      'krem z filtrem',
      'powerbank',
      'okulary przeciwsłoneczne',
      'worki na śmieci',
      'bidon na wodę',
      'suszarka',
      'klapki pod prysznic',
    ],
    rowery: [
      'rower',
      'zapasowa dętka',
      'zestaw naprawczy',
      'pompka rowerowa',
      'uchwyt na telefon',
      'lampki rowerowe',
      'licznik',
      'odzież rowerowa',
      'scyzoryk',
      'sakwa',
      'odblaski',
    ],
    autostop: [
      'duży plecak',
      'namiot',
      'karimata',
      'śpiwór',
      'sztućce',
      'scyzoryk',
      'duży kubek',
      'grzałka do wody',
      'sznurek',
      'taśma klejąca',
      'czołówka',
      'odblaski',
      'karton i markery',
      'jedzenie długoterminowe',
    ],
    fotografia: [
      'aparat',
      'karta pamięci',
      'statyw',
      'obiektywy',
      'ładowarka do aparatu',
      'pasek do aparatu',
      'etui na aparat',
    ],
    plażowanie: [
      'ręcznik plażowy',
      'parasol plażowy',
      'mata plażowa',
      'torba termiczna na żywność',
      'duża torba',
      'strój kąpielowy',
      'leżak',
    ],
    kemping: [
      'namiot',
      'karimata',
      'śpiwór',
      'taśma izolacyjna',
      'lampa zewnętrzna',
      'latarka',
      'poduszka',
      'naczynia kempingowe',
      'sztućce',
      'kubek',
      'palnik gazowy',
      'grzałka do wody',
      'zapalniczka',
      'scyzoryk',
      'sznurek',
    ],
    trekking: [
      'buty trekkingowe',
      'skarpetki trekkingowe',
      'duży plecak',
      'kije trekkingowe',
      'czołówka',
      'rękawiczki',
    ],
    wspinaczka: [
      'kask wspinaczkowy',
      'uprząż wspinaczkowa',
      'karabinek',
      'przyrząd asekuracyjny',
      'rękawiczki wspinaczkowe',
      'liny',
      'buty wspinaczkowe',
      'magnezja',
      'woreczek na magnezję',
    ],
    dziecko: [
      'pampersy',
      'mokre chusteczki',
      'zabawki',
      'ubranka dla dziecka',
      'kocyk',
      'mleko modyfikowane',
      'butelka',
      'podkłady higieniczne',
      'smoczek',
      'wózek dziecięcy',
      'nosidełko',
      'jedzenie dla dziecka',
      'pielucha',
    ],
  };

  getPackingList(activity: string): string[] {
    return this.packingLists[activity] || [];
  }
}

